#!/usr/bin/python3
from bytenigma.bytenigma import encrypt
from sys import stderr, argv
from traceback import format_exc
from base64 import b64encode, b64decode
from bytenigma.bytenigma import encrypt
from json import loads

def parse_input(enigma_dict):
    try:
        input_string = b64decode(enigma_dict['input'])
        return input_string, enigma_dict['rotors']
    except:
        print('error parsing json', file=stderr)
        print(format_exc(), file=stderr)
        exit(1)

def assemble_output(byte_string):
    output_string = b64encode(byte_string).decode()
    return '{\n\t"output": "'+output_string+'"\n}'

def bytenigma(input_file):
    #takes a json file as an input and outputs a json of the from { "output": output }
    try:
        file_content = ''
        with open(input_file, 'r') as f:
            file_content = loads(f.read())
        input_string, rotors = parse_input(file_content)
        cipher = encrypt(input_string, rotors)
        return assemble_output(cipher)
    except:
        print('error with encryption', file=stderr)
        print(format_exc(), file=stderr)
        exit(1)
    


if __name__ == "__main__":
    print(bytenigma(argv[1]))